### ISSUE TITLE
Proxmox Backup Server LXC install

### ISSUE THREAD

**Issue by mixpc** [asylumexp/Proxmox#120]
### ✅ Have you read and understood the above guidelines?

Yes

### 📜 What is the name of the script you are using?

Proxmox Backup Server LXC

### 📂 What was the exact command used to execute the script?

root@mymachine:/home/myuser# bash -xc "$(wget -qLO - https://github.com/asylumexp/Proxmox/raw/main/ct/proxmox-backup-server.sh)"

### 📝 Provide a clear and concise description of the issue.

Running Proxmox VE on a Raspberry Pi 5 with Raspberry Pi OS 64-bit Lite. When trying to install Proxmox Backup Server LXC, the script will produce the message below:

`[ERROR] in line 29: exit code 0: while executing command git clone https://github.com/wofferl/proxmox-backup-arm64
`

### ⚙️ What settings are you using?

- [ ] Default Settings
- [x] Advanced Settings

### 🔄 Steps to reproduce the issue.

Linux Distro is Raspberry Pi OS
Basically, running the script as root and choosing default install

### ❌ Paste the full error output (if available).

The verbose log for the advanced install shows the following:
```Running hooks in /etc/ca-certificates/update.d...
done.
  ✔️  Installed Dependencies
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Reading package lists... Done
bash: line 29: git: command not found
 ⠹
[ERROR] in line 29: exit code 0: while executing command git clone https://github.com/wofferl/proxmox-backup-arm64
+ exit 127
+ exit_script
+ exit_code=127
+ '[' 127 -ne 0 ']'
+ case $exit_code in
+ post_update_to_api failed 'Unknown error, exit code: 127 in create_lxc.sh'
+ command -v curl
+ '[' false = true ']'
+ local API_URL=http://api.community-scripts.org/upload/updatestatus
+ local status=failed
+ local 'error=Unknown error, exit code: 127 in create_lxc.sh'
++ cat
+ JSON_PAYLOAD='{
    "status": "failed",
    "error": "Unknown error, exit code: 127 in create_lxc.sh",
    "random_id": "aea4f861-4a08-46ca-b2f2-cf681a0832cb"
}'
++ curl -s -w '%{http_code}' -L -X POST http://api.community-scripts.org/upload/updatestatus --post301 --post302 -H 'Content-Type: application/json' -d '{
    "status": "failed",
    "error": "Unknown error, exit code: 127 in create_lxc.sh",
    "random_id": "aea4f861-4a08-46ca-b2f2-cf681a0832cb"
}'
+ RESPONSE='{"message":"Record updated successfully"}
200'
+ POST_UPDATE_DONE=true
```

The verbose log for the **default** install shows the following:
```
  ✔️  Set up Container OS
  ✔️  Network Connected: 192.168.68.152
  ✔️  IPv4 Internet Connected
  ✖️  IPv6 Internet Not Connected
  ✔️  DNS Resolved github.com to 140.82.121.3
  ✔️  Updated Container OS
  ✔️  Installed Dependencies
 ⠋bash: line 29: git: command not found
 ⠙
[ERROR] in line 29: exit code 0: while executing command git clone https://github.com/wofferl/proxmox-backup-arm64
+ exit 127
+ exit_script
+ exit_code=127
+ '[' 127 -ne 0 ']'
+ case $exit_code in
+ post_update_to_api failed 'Unknown error, exit code: 127 in create_lxc.sh'
+ command -v curl
+ '[' false = true ']'
+ local API_URL=http://api.community-scripts.org/upload/updatestatus
+ local status=failed
+ local 'error=Unknown error, exit code: 127 in create_lxc.sh'
++ cat
+ JSON_PAYLOAD='{
    "status": "failed",
    "error": "Unknown error, exit code: 127 in create_lxc.sh",
    "random_id": "f6b6cfac-1612-4b27-80d2-171cd6a04532"
}'
++ curl -s -w '%{http_code}' -L -X POST http://api.community-scripts.org/upload/updatestatus --post301 --post302 -H 'Content-Type: application/json' -d '{
    "status": "failed",
    "error": "Unknown error, exit code: 127 in create_lxc.sh",
    "random_id": "f6b6cfac-1612-4b27-80d2-171cd6a04532"
}'
+ RESPONSE='{"message":"Record updated successfully"}
200'
+ POST_UPDATE_DONE=true
```

### 🖼️ Additional context (optional).

It seems **git** is missing? That might be the cause? Or maybe the script is arm64-friendly but not Raspberry Pi 5-friendly (on a RPi5)?

**Comment by asylumexp** [comment]
Should work now will test in a minute, you were right forgot to add git to dependencies.

**Comment by vg8020** [comment]
@asylumexp Hi, thank you for your interest and action. Kindly note, I just retried and noted the following:
```
    ____                                             ____             __                    _____                          
   / __ \_________  _  ______ ___  ____  _  __      / __ )____ ______/ /____  ______       / ___/___  ______   _____  _____
  / /_/ / ___/ __ \| |/_/ __ `__ \/ __ \| |/_/_____/ __  / __ `/ ___/ //_/ / / / __ \______\__ \/ _ \/ ___/ | / / _ \/ ___/
 / ____/ /  / /_/ />  </ / / / / / /_/ />  </_____/ /_/ / /_/ / /__/ ,< / /_/ / /_/ /_____/__/ /  __/ /   | |/ /  __/ /    
/_/   /_/   \____/_/|_/_/ /_/ /_/\____/_/|_|     /_____/\__,_/\___/_/|_|\__,_/ .___/     /____/\___/_/    |___/\___/_/     
                                                                            /_/                                            
  ⚙️  Using Default Settings on node beta
  🖥️  Operating System: debian
  🌟  Version: 12
  📦  Container Type: Unprivileged
  💾  Disk Size: 10 GB
  🧠  CPU Cores: 2
  🛠️  RAM Size: 2048 MiB
  🆔  Container ID: 104
  🚀  Creating a Proxmox-Backup-Server LXC using the above default settings
  
  ✔️  Using local for Template Storage.
  ✔️  Using local for Container Storage.
  ✔️  Downloaded LXC Template
  ✔️  LXC Template is ready to use.
  ✔️  LXC Container 104 was successfully created.
  ✔️  Started LXC Container
  ✔️  Set up Container OS
  ✔️  Network Connected: 192.168.68.162 
  ✔️  IPv4 Internet Connected
  ✖️  IPv6 Internet Not Connected
  ✔️  DNS Resolved github.com to 140.82.121.3
  ✔️  Updated Container OS
  ✔️  Installed Dependencies
 ⠙Cloning into 'proxmox-backup-arm64'...
 ⠧remote: Enumerating objects: 974, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 974 (delta 47), reused 28 (delta 28), pack-reused 919 (from 2)
Receiving objects: 100% (974/974), 178.36 KiB | 1.78 MiB/s, done.
Resolving deltas: 100% (591/591), done.
./build.sh: line 175: dpkg-architecture: command not found
 ⠹
[ERROR] in line 32: exit code 0: while executing command ./build.sh download
root@beta:~# 
```

Didn't use debug mode, and went just with default settings, this is just the output, but it seems there's an issue with dpkg-architecture.

Thank you!

**Comment by vg8020** [comment]
@asylumexp Hi, thank you for your interest and action. Kindly note, I just retried and noted the following:
```
    ____                                             ____             __                    _____                          
   / __ \_________  _  ______ ___  ____  _  __      / __ )____ ______/ /____  ______       / ___/___  ______   _____  _____
  / /_/ / ___/ __ \| |/_/ __ `__ \/ __ \| |/_/_____/ __  / __ `/ ___/ //_/ / / / __ \______\__ \/ _ \/ ___/ | / / _ \/ ___/
 / ____/ /  / /_/ />  </ / / / / / /_/ />  </_____/ /_/ / /_/ / /__/ ,< / /_/ / /_/ /_____/__/ /  __/ /   | |/ /  __/ /    
/_/   /_/   \____/_/|_/_/ /_/ /_/\____/_/|_|     /_____/\__,_/\___/_/|_|\__,_/ .___/     /____/\___/_/    |___/\___/_/     
                                                                            /_/                                            
  ⚙️  Using Default Settings on node beta
  🖥️  Operating System: debian
  🌟  Version: 12
  📦  Container Type: Unprivileged
  💾  Disk Size: 10 GB
  🧠  CPU Cores: 2
  🛠️  RAM Size: 2048 MiB
  🆔  Container ID: 104
  🚀  Creating a Proxmox-Backup-Server LXC using the above default settings
  
  ✔️  Using local for Template Storage.
  ✔️  Using local for Container Storage.
  ✔️  Downloaded LXC Template
  ✔️  LXC Template is ready to use.
  ✔️  LXC Container 104 was successfully created.
  ✔️  Started LXC Container
  ✔️  Set up Container OS
  ✔️  Network Connected: 192.168.68.162 
  ✔️  IPv4 Internet Connected
  ✖️  IPv6 Internet Not Connected
  ✔️  DNS Resolved github.com to 140.82.121.3
  ✔️  Updated Container OS
  ✔️  Installed Dependencies
 ⠙Cloning into 'proxmox-backup-arm64'...
 ⠧remote: Enumerating objects: 974, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 974 (delta 47), reused 28 (delta 28), pack-reused 919 (from 2)
Receiving objects: 100% (974/974), 178.36 KiB | 1.78 MiB/s, done.
Resolving deltas: 100% (591/591), done.
./build.sh: line 175: dpkg-architecture: command not found
 ⠹
[ERROR] in line 32: exit code 0: while executing command ./build.sh download
root@beta:~# 
```

Didn't use debug mode, and went just with default settings, this is just the output, but it seems there's an issue with dpkg-architecture.

Thank you!

**Comment by asylumexp** [comment]
Oops forgot to test it, works now.

**Comment by bhouseski** [comment]
tried this earlier and am still have an error (see below)

  Using Advanced Settings on node PMOX1
  🖥️  Operating System: debian
  🌟  Version: 12
  📦  Container Type: Privileged
  🔐  Root Password: ********
  🆔  Container ID: 104
  🏠  Hostname: proxmox-backup-server
  💾  Disk Size: 10 GB
  🧠  CPU Cores: 2
  🛠️  RAM Size: 2048 MiB
  🌉  Bridge: vmbr0
  📡  IP Address: 10.0.1.246/24
  🌐  Gateway IP Address: 10.0.1.1
  📡  APT-Cacher IP Address: Default
  🚫  Disable IPv6: no
  ⚙️  Interface MTU Size: Default
  🔍  DNS Search Domain: Host
  📡  DNS Server IP Address: Host
  🏷️  Vlan: Default
  📡  Tags: community-script;backup
  🔑  Root SSH Access: no
  🔍  Verbose Mode: no
  🚀  Creating a Proxmox-Backup-Server LXC using the above advanced settings
  ✔️  Using local for Template Storage.
  ✔️  Using Ceph_pool for Container Storage.
  ✔️  LXC Template is ready to use.
  ✔️  LXC Container 104 was successfully created.
  ✔️   Started LXC Container
bash: warning: setlocale: LC_ALL: cannot change locale (en_CA.UTF-8)
  ✔️  Set up Container OS
  ✔️  Network Connected: 10.0.1.246 
  ✔️  IPv4 Internet Connected
  ✖️  IPv6 Internet Not Connected
  ✔️  DNS Resolved github.com to 140.82.112.3
  ✔️  Updated Container OS
  ✔️  Core dependencies installed
  ✔️  Installed Dependencies
 ⠋Cloning into 'proxmox-backup-arm64'...ience) 
 ⠸remote: Enumerating objects: 1007, done.
remote: Counting objects: 100% (88/88), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 1007 (delta 65), reused 51 (delta 39), pack-reused 919 (from 2)
Receiving objects: 100% (1007/1007), 189.59 KiB | 2.46 MiB/s, done.
Resolving deltas: 100% (609/609), done.
 ⠴
[ERROR] in line 49: exit code 0: while executing command "$@" > /dev/null 2>&1
curl: (22) The requested URL returned error: 400
/dev/fd/63: line 71: SPINNER_PID: unbound variable
